language: generic 
sudo: required
services:
  - docker 

before_install: 
  - docker build -t omarosama10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omarosama10/react-test npm test

after_success: 
  - docker build -t omarosama10/multi-client ./client 
  - docker build -t omarosama10/multi-nginx ./nginx
  - docker build -t omarosama10/multi-server ./server
  - docker build -t omarosama10/multi-worker ./worker
  # login to docker docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to dockerhub
  - docker push omarosama10/multi-client 
  - docker push omarosama10/multi-nginx
  - docker push omarosama10/multi-server
  - docker push omarosama10/multi-worker
